<?php

namespace Sistema\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PayULatamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayULatamRepository extends EntityRepository
{
}
