fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Sistema\UserBundle\Entity\User

    # service:
    #     mailer: fos_user.mailer.twig_swift

    # from_email:
    #     address:        %mail_from%
    #     sender_name:    Crear Negocio

    # registration:
    #     confirmation:
    #         enabled:    true
    #         from_email:
    #             address:        %mail_from%
    #             sender_name:    Mi Negocio Registro 
    #         template: FOSUserBundle:Registration:email.html.twig

    # resetting:
    #     email:
    #         from_email:
    #             address:        %mail_from%
    #             sender_name:    Solicitud de Cambio de Contraseña
    #         template: FOSUserBundle:Resetting:email.txt.twig