sistema_front:
    resource: "@SistemaFrontBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_back:
    resource: "@SistemaBackBundle/Controller/"
    type:     annotation
    prefix:   /

mw_simple_admin_crud:
    resource: "@MWSimpleAdminCrudBundle/Controller/"
    type:     annotation
    prefix:   /admin

usuario:
    resource: "@SistemaUserBundle/Controller/"
    type:     annotation
    prefix:   /admin