sistema_front:
    resource: "@SistemaFrontBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_back:
    resource: "@SistemaBackBundle/Controller/"
    type:     annotation
    prefix:   /

